name: Create release on tag push
description: test
inputs:
  GITHUB_TOKEN:
    description: "Github token"
    required: true

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Create Release
      uses: actions/create-release@v1
      env:
          GH_TOKEN: ${{inputs.GITHUB_TOKEN}}
      with:
        tag_name: ${{github.ref_name}}
        release_name: Datenstand ${{github.ref_name}}
        body: Datenstand ${{github.ref_name}} inklusive aktualisierter Metadaten
        draft: false
        prerelease: false
