name: Create release on tag push
description: test

runs:
  using: "composite"
  steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Create Release
      env:
        GITHUB_TOKEN: ${{ github.token }}
      uses: actions/create-release@v1
      with:
        tag_name: ${{github.ref_name}}
        release_name: Datenstand ${{github.ref_name}}
        body: Datenstand ${{github.ref_name}} inklusive aktualisierter Metadaten
        draft: false
        prerelease: false
