on:
  workflow_call:
permissions:
  contents: write
jobs:
  create_release:
    name: Create release on tag push
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        env:
          GH_TOKEN: ${{secrets.GITHUB_TOKEN}}
        uses: robert-koch-institut/OpenData-Workflows/Create_release_on_tag_push@main
        with:
          REF_NAME: ${{github.ref_name}}